stages:
  - test
  - build
  - deploy

Docker build stage:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cp ${ENV_STAGE} ./configs/.env      
    - cp ${CHROME_SETTINGS} ./configs/chrome/chrome.json  
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - echo "Build widgets"
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-verification-checker:stage -f ./build/package/production/Dockerfile .
    - echo "Push widgets"
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-verification-checker:stage
  tags:
    - invest-docker
  only:
    - stage

Deploy to stage:
  stage: deploy
  script:
    - cp ${ENV_STAGE} ./configs/.env  
    - cp ${CHROME_SETTINGS} ./configs/chrome/chrome.json      
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - cd ~/investments-stage
    - docker-compose pull
    - docker-compose up -d --force-recreat
  tags:
    - invest-stage-shell
  only:
    - stage


Docker build prod:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cp ${ENV_STAGE} ./configs/.env      
    - cp ${CHROME_SETTINGS} ./configs/chrome/chrome.json  
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - echo "Build widgets"
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-verification-checker:prod -f ./build/package/production/Dockerfile .
    - echo "Push widgets"
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-verification-checker:prod
  tags:
    - invest-docker
  only:
    - master

Deploy to prod:
  stage: deploy
  script:
    - cp ${ENV_STAGE} ./configs/.env      
    - cp ${CHROME_SETTINGS} ./configs/chrome/chrome.json  
    - ssh prod "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY} && cd /home/gitlab-runner/investments-prod && docker-compose pull && docker-compose up -d --force-recreat"
  tags:
    - invest-stage-shell
  only:
    - master